# @format

services:
   burak-react:
      container_name: cooking
      restart: always
      image: node:20.10.0
      ports:
         - 4008:2000
      environment:
         - PORT=2000

      volumes:
         - ./:/usr/src/burak-react
      working_dir: /usr/src/burak-react
      networks:
         - monorepo-network

      # FOR PRODUCTION
      command: bash -c "yarn && yarn run build && yarn run start"

networks:
   monorepo-network:
      driver: bridge
