# @format

services:
   burak-react:
      container_name: cooking-frontend
      restart: always
      image: node:20.10.0
      ports:
         - 4008:2000
      volumes:
         - ./:/usr/src/burak-react
      working_dir: /usr/src/burak-react
      networks:
         - app-network
      environment:
         - REACT_APP_API_URL=http://localhost:4007

           - PORT=2000
      command: bash -c "yarn && yarn run build && yarn run start"

networks:
   app-network:
      driver: bridge
