# @format

services:
   burak-react:
      container_name: cooking-frontend
      restart: always
      image: node:20.10.0
      ports:
         - 4008:3000
      volumes:
         - ./:/usr/src/burak-react
      working_dir: /usr/src/burak-react
      networks:
         - client-network
      environment:
         - REACT_APP_API_URL=http://cooking-api:3003
         - PORT=3000

      command: bash -c "yarn && yarn run build && yarn run start"
