# @format

services:
   cooking:
      container_name: cooking
      restart: always
      image: node:20.10.0
      ports:
         - 4000:3000
      environment:
         - PORT=3000

      volumes:
         - ./:/usr/src/cooking
      working_dir: /usr/src/cooking
      networks:
         - client-network

      # FOR PRODUCTION
      command: bash -c "yarn && yarn run build && yarn run start"

networks:
   monorepo-network:
      driver: bridge
